# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
#  - oldrel
  - release
#  - devel
sudo: false
cache: packages

# env:
#  global:
#    - RETICULATE_PYTHON=""

before_install:
  - which python3

