# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
#  - oldrel
  - release
#  - devel
sudo: required
cache: packages

# inspiration:
#  https://github.com/mushkevych/scheduler/blob/2.0/.travis.yml
#  https://github.com/rstudio/reticulate/blob/master/.travis.yml
addons:
  apt:
    sources:
    # apt source hosting Python3.5 and 3.6
    #- deadsnakes
    - sourceline: 'ppa:jonathonf/python-3.6'
    packages:
    # Travis-ci has a known issue with Python3.5 and 3.6
    - python3.6
    #- python3-setuptools
    #- python3-pip

#env:
#  global:
#    - RETICULATE_PYTHON="/opt/pyenv/shims/python3.6"

before_install:
  - which python3.6
  - python3.6 --version
  - sudo -E curl https://bootstrap.pypa.io/ez_setup.py -o - | python3.6 && python3.6 -m easy_install pip
  # - pip3 install --user --upgrade pip
  # - pip3 --version
  - python3.6 -m pip -V
  - python3.6 -m pip install --user altair==2.0.0rc1

#before_script:


